language: nodejs

nodejs:
  - 12
  - 14

env:
  global:
    - NODE_ENV: test
    - CODECOV_TOKEN: "abb0203e-ecc3-4b54-b0aa-9d8a1fee1289"

before_script:
  - npm install -g npm@latest
  - npm install

after_script:
  - npm test && npm run coverage
  - if [ -f coverage/coverage-final.json ]; then codecov; fi
